# Path to project config
project_config: model/v1/0509split.yml
# Path to onnx model weights
model_path: model/v1/model.onnx
# Score threshold for the output bounding box
threshold: 0.2
# IoU threshold for the output bounding box
iou_threshold: 0.2
# network param
compound_coef: 2
