project_config: /home/mazheng/waste-detection/Yet-Another-EfficientDet-Pytorch/inference_tool/projects/0509split.yml
# Path to project config
model_path: /home/mazheng/waste-detection/Yet-Another-EfficientDet-Pytorch/inference_tool/weights/efficientdet-d2.onnx
# Path to onnx model weights
img_path: /home/mazheng/waste-detection/Yet-Another-EfficientDet-Pytorch/inference_tool/examples/fig/DLLJ1796.jpg
# Path to image or image dir
output_path: /home/mazheng/waste-detection/Yet-Another-EfficientDet-Pytorch/inference_tool/output/fig
# output_dir
threshold: 0.2
# Score threshold for the output bounding box
iou_threshold: 0.2
# IoU threshold for the output bounding box
compound_coef: 2
# network param